In [3]:
import pandas as pd
import numpy as np

In [5]:
cd

C:\Users\cvr

In [24]:
import pandas as pd
import numpy as np
hd=pd.read_csv('wine_data.csv')

In [26]:
hd.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,11.6,0.580,0.66,2.20,0.074,10.0,47.0,1.00080,3.25,0.57,9.0,3
1,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3
2,7.4,1.185,0.00,4.25,0.097,5.0,14.0,0.99660,3.63,0.54,10.7,3
3,10.4,0.440,0.42,1.50,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3
4,8.3,1.020,0.02,3.40,0.084,6.0,11.0,0.99892,3.48,0.49,11.0,3

In [28]:
hd.tail()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
20995,9.7,1.02,0.91,50.0,0.412,114.6,181.7,1.02085,3.30,0.89,12.0,9
20996,10.2,0.61,0.88,53.8,0.250,62.4,204.7,1.02776,3.52,1.14,9.7,9
20997,13.4,0.46,1.04,52.1,0.449,63.0,273.5,1.02618,2.89,1.76,9.3,9
20998,6.6,1.03,1.09,25.3,0.138,179.8,295.0,1.02476,2.94,1.54,12.9,9
20999,9.3,0.93,1.32,33.6,0.412,128.7,290.1,1.02182,3.16,1.42,13.0,9

In [30]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21000 entries, 0 to 20999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         21000 non-null  float64
 1   volatile_acidity      21000 non-null  float64
 2   citric_acid           21000 non-null  float64
 3   residual_sugar        21000 non-null  float64
 4   chlorides             21000 non-null  float64
 5   free_sulfur_dioxide   21000 non-null  float64
 6   total_sulfur_dioxide  21000 non-null  float64
 7   density               21000 non-null  float64
 8   pH                    21000 non-null  float64
 9   sulphates             21000 non-null  float64
 10  alcohol               21000 non-null  float64
 11  quality               21000 non-null  int64
dtypes: float64(11), int64(1)
memory usage: 1.9 MB

In [38]:
hd.shape

(21000, 12)

In [44]:
hd.columns

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [46]:
hd.isnull()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
20995,False,False,False,False,False,False,False,False,False,False,False,False
20996,False,False,False,False,False,False,False,False,False,False,False,False
20997,False,False,False,False,False,False,False,False,False,False,False,False
20998,False,False,False,False,False,False,False,False,False,False,False,False
20999,False,False,False,False,False,False,False,False,False,False,False,False

In [48]:
hd.isnull().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [52]:
hd.iloc[0]

fixed_acidity           11.6000
volatile_acidity         0.5800
citric_acid              0.6600
residual_sugar           2.2000
chlorides                0.0740
free_sulfur_dioxide     10.0000
total_sulfur_dioxide    47.0000
density                  1.0008
pH                       3.2500
sulphates                0.5700
alcohol                  9.0000
quality                  3.0000
Name: 0, dtype: float64

In [54]:
hd.pH.unique()

array([3.25, 3.16, 3.63, 3.38, 3.48, 3.5 , 3.32, 3.31, 3.4 , 3.55, 3.02,
       3.53, 3.23, 3.24, 2.89, 2.87, 3.2 , 3.04, 3.14, 2.93, 3.05, 3.42,
       2.9 , 3.37, 3.44, 3.01, 3.03, 2.98, 3.08, 3.15, 3.1 , 3.58, 2.96,
       2.91, 2.85, 2.99, 3.21, 3.39, 3.11, 3.34, 3.47, 2.78, 2.94, 3.19,
       3.09, 3.18, 3.17, 2.95, 3.45, 3.29, 3.65, 3.22, 3.13, 3.51, 3.26,
       3.56, 2.92, 3.07, 3.33, 2.86, 3.28, 3.12, 3.41, 2.97, 3.  , 3.3 ,
       3.46, 3.27, 2.88, 2.84, 3.06, 3.35, 3.36, 3.62, 2.81, 3.6 , 3.57,
       2.8 , 3.43, 3.52, 3.59, 2.83, 3.68, 2.79, 3.61, 3.54, 3.49, 2.82,
       3.72, 3.9 , 3.75, 2.74, 3.66, 2.75, 3.64, 2.77, 3.71, 3.67, 3.74,
       3.69, 3.77, 3.79, 3.81, 3.85, 3.7 , 3.78, 4.01, 2.72, 3.8 , 3.76,
       3.82, 3.73])

In [58]:
hd.pH.drop_duplicates()

0        3.25
1        3.16
2        3.63
3        3.38
4        3.48
         ...
10453    2.72
10513    3.80
11590    3.76
12434    3.82
13250    3.73
Name: pH, Length: 112, dtype: float64

In [60]:
hd.drop_duplicates()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,11.6,0.580,0.66,2.20,0.074,10.0,47.0,1.00080,3.25,0.57,9.0,3
1,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3
2,7.4,1.185,0.00,4.25,0.097,5.0,14.0,0.99660,3.63,0.54,10.7,3
3,10.4,0.440,0.42,1.50,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3
4,8.3,1.020,0.02,3.40,0.084,6.0,11.0,0.99892,3.48,0.49,11.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
20985,10.3,1.080,0.53,50.80,0.290,84.2,345.0,1.00356,3.17,1.38,13.8,9
20987,11.4,0.900,0.64,51.20,0.417,197.1,241.8,1.01707,3.31,1.33,11.3,9
20988,11.8,1.100,0.84,46.50,0.255,198.4,130.0,1.01697,3.11,0.87,10.8,9
20993,13.0,0.580,1.22,52.80,0.247,93.0,190.7,1.01922,3.38,1.24,9.9,9
20994,12.8,0.850,1.12,44.90,0.188,215.3,253.3,1.02192,3.13,0.81,11.4,9

In [64]:
hd.describe()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
count,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000,21000.000000
mean,9.797079,0.774796,0.793870,31.289348,0.200245,129.442333,229.008762,1.009972,3.158712,1.020641,11.291716,6.000000
std,2.413919,0.365015,0.384833,19.015391,0.124933,77.167262,100.183265,0.012032,0.171371,0.408304,1.182198,2.000048
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,7.600000,0.430000,0.410000,9.800000,0.072000,45.000000,150.000000,0.997417,3.030000,0.620000,10.400000,4.000000
50%,10.000000,0.830000,0.870000,37.600000,0.205000,145.800000,240.500000,1.012200,3.150000,1.080000,11.300000,6.000000
75%,11.800000,1.080000,1.110000,46.800000,0.298000,194.325000,311.625000,1.019840,3.270000,1.360000,12.200000,8.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [72]:
hd.rename(columns={'total_sulfur_dioxide':'total'})

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total,density,pH,sulphates,alcohol,quality
0,11.6,0.580,0.66,2.20,0.074,10.0,47.0,1.00080,3.25,0.57,9.0,3
1,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3
2,7.4,1.185,0.00,4.25,0.097,5.0,14.0,0.99660,3.63,0.54,10.7,3
3,10.4,0.440,0.42,1.50,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3
4,8.3,1.020,0.02,3.40,0.084,6.0,11.0,0.99892,3.48,0.49,11.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
20995,9.7,1.020,0.91,50.00,0.412,114.6,181.7,1.02085,3.30,0.89,12.0,9
20996,10.2,0.610,0.88,53.80,0.250,62.4,204.7,1.02776,3.52,1.14,9.7,9
20997,13.4,0.460,1.04,52.10,0.449,63.0,273.5,1.02618,2.89,1.76,9.3,9
20998,6.6,1.030,1.09,25.30,0.138,179.8,295.0,1.02476,2.94,1.54,12.9,9
20999,9.3,0.930,1.32,33.60,0.412,128.7,290.1,1.02182,3.16,1.42,13.0,9

In [82]:
hd.mean()

fixed_acidity             9.797079
volatile_acidity          0.774796
citric_acid               0.793870
residual_sugar           31.289348
chlorides                 0.200245
free_sulfur_dioxide     129.442333
total_sulfur_dioxide    229.008762
density                   1.009972
pH                        3.158712
sulphates                 1.020641
alcohol                  11.291716
quality                   6.000000
dtype: float64

In [84]:
hd.std()

fixed_acidity             2.413919
volatile_acidity          0.365015
citric_acid               0.384833
residual_sugar           19.015391
chlorides                 0.124933
free_sulfur_dioxide      77.167262
total_sulfur_dioxide    100.183265
density                   0.012032
pH                        0.171371
sulphates                 0.408304
alcohol                   1.182198
quality                   2.000048
dtype: float64

In [86]:
hd.median()

fixed_acidity            10.0000
volatile_acidity          0.8300
citric_acid               0.8700
residual_sugar           37.6000
chlorides                 0.2050
free_sulfur_dioxide     145.8000
total_sulfur_dioxide    240.5000
density                   1.0122
pH                        3.1500
sulphates                 1.0800
alcohol                  11.3000
quality                   6.0000
dtype: float64

In [90]:
hd.mode()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,6.8,0.28,0.3,2.0,0.044,29.0,111.0,0.9972,3.16,0.5,11.5,3
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9976,NaN,NaN,NaN,4
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9

In [106]:
hd['pH'].mean()

3.1587119047619048

In [108]:
hd['pH'].mode()

0    3.16
Name: pH, dtype: float64

In [110]:
hd['pH'].median()

3.15

In [114]:
hd['pH'].std()

0.17137100174822836

In [116]:
hd.corr()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
fixed_acidity,1.000000,0.562166,0.596388,0.653793,0.601889,0.653679,0.506634,0.625238,-0.254357,0.579008,0.167870,0.037545
volatile_acidity,0.562166,1.000000,0.634551,0.730159,0.622915,0.746446,0.622015,0.673260,-0.213949,0.660118,0.375957,0.020286
citric_acid,0.596388,0.634551,1.000000,0.765075,0.660209,0.700625,0.636895,0.740276,-0.185421,0.645684,0.358110,0.052341
residual_sugar,0.653793,0.730159,0.765075,1.000000,0.747546,0.781699,0.748704,0.787859,-0.254473,0.679813,0.349538,0.049734
chlorides,0.601889,0.622915,0.660209,0.747546,1.000000,0.647345,0.606934,0.715181,-0.113158,0.603356,0.278020,0.052905
free_sulfur_dioxide,0.653679,0.746446,0.700625,0.781699,0.647345,1.000000,0.701708,0.713815,-0.220648,0.688007,0.325231,0.053021
total_sulfur_dioxide,0.506634,0.622015,0.636895,0.748704,0.606934,0.701708,1.000000,0.640192,-0.253135,0.615716,0.369074,0.035975
density,0.625238,0.673260,0.740276,0.787859,0.715181,0.713815,0.640192,1.000000,-0.251992,0.642063,0.318679,0.038473
pH,-0.254357,-0.213949,-0.185421,-0.254473,-0.113158,-0.220648,-0.253135,-0.251992,1.000000,-0.233409,-0.106879,-0.002383
sulphates,0.579008,0.660118,0.645684,0.679813,0.603356,0.688007,0.615716,0.642063,-0.233409,1.000000,0.402166,0.047728
alcohol,0.167870,0.375957,0.358110,0.349538,0.278020,0.325231,0.369074,0.318679,-0.106879,0.402166,1.000000,0.081891
quality,0.037545,0.020286,0.052341,0.049734,0.052905,0.053021,0.035975,0.038473,-0.002383,0.047728,0.081891,1.000000

In [120]:
hd.fillna(hd.mean())

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,11.6,0.580,0.66,2.20,0.074,10.0,47.0,1.00080,3.25,0.57,9.0,3
1,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3
2,7.4,1.185,0.00,4.25,0.097,5.0,14.0,0.99660,3.63,0.54,10.7,3
3,10.4,0.440,0.42,1.50,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3
4,8.3,1.020,0.02,3.40,0.084,6.0,11.0,0.99892,3.48,0.49,11.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
20995,9.7,1.020,0.91,50.00,0.412,114.6,181.7,1.02085,3.30,0.89,12.0,9
20996,10.2,0.610,0.88,53.80,0.250,62.4,204.7,1.02776,3.52,1.14,9.7,9
20997,13.4,0.460,1.04,52.10,0.449,63.0,273.5,1.02618,2.89,1.76,9.3,9
20998,6.6,1.030,1.09,25.30,0.138,179.8,295.0,1.02476,2.94,1.54,12.9,9
20999,9.3,0.930,1.32,33.60,0.412,128.7,290.1,1.02182,3.16,1.42,13.0,9

In [122]:
hd.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,11.6,0.580,0.66,2.20,0.074,10.0,47.0,1.00080,3.25,0.57,9.0,3
1,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3
2,7.4,1.185,0.00,4.25,0.097,5.0,14.0,0.99660,3.63,0.54,10.7,3
3,10.4,0.440,0.42,1.50,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3
4,8.3,1.020,0.02,3.40,0.084,6.0,11.0,0.99892,3.48,0.49,11.0,3

In [124]:
hd.index

RangeIndex(start=0, stop=21000, step=1)

In [126]:
hd.T

,0,1,2,3,4,5,6,7,8,9,...,20990,20991,20992,20993,20994,20995,20996,20997,20998,20999
fixed_acidity,11.6000,10.4000,7.4000,10.40000,8.30000,7.60000,6.80000,7.30000,7.10000,6.700,...,12.30000,10.20000,12.900,13.00000,12.80000,9.70000,10.20000,13.40000,6.60000,9.30000
volatile_acidity,0.5800,0.6100,1.1850,0.44000,1.02000,1.58000,0.81500,0.98000,0.87500,0.760,...,1.21000,0.61000,0.900,0.58000,0.85000,1.02000,0.61000,0.46000,1.03000,0.93000
citric_acid,0.6600,0.4900,0.0000,0.42000,0.02000,0.00000,0.00000,0.05000,0.05000,0.020,...,0.68000,0.88000,1.160,1.22000,1.12000,0.91000,0.88000,1.04000,1.09000,1.32000
residual_sugar,2.2000,2.1000,4.2500,1.50000,3.40000,2.10000,1.20000,2.10000,5.70000,1.800,...,59.10000,53.80000,51.200,52.80000,44.90000,50.00000,53.80000,52.10000,25.30000,33.60000
chlorides,0.0740,0.2000,0.0970,0.14500,0.08400,0.13700,0.26700,0.06100,0.08200,0.078,...,0.32800,0.25000,0.309,0.24700,0.18800,0.41200,0.25000,0.44900,0.13800,0.41200
free_sulfur_dioxide,10.0000,5.0000,5.0000,34.00000,6.00000,5.00000,16.00000,20.00000,3.00000,6.000,...,232.00000,62.40000,196.900,93.00000,215.30000,114.60000,62.40000,63.00000,179.80000,128.70000
total_sulfur_dioxide,47.0000,16.0000,14.0000,48.00000,11.00000,9.00000,29.00000,49.00000,14.00000,12.000,...,396.00000,204.70000,172.300,190.70000,253.30000,181.70000,204.70000,273.50000,295.00000,290.10000
density,1.0008,0.9994,0.9966,0.99832,0.99892,0.99476,0.99471,0.99705,0.99808,0.996,...,1.03428,1.02776,1.030,1.01922,1.02192,1.02085,1.02776,1.02618,1.02476,1.02182
pH,3.2500,3.1600,3.6300,3.38000,3.48000,3.50000,3.32000,3.31000,3.40000,3.550,...,3.12000,3.52000,3.100,3.38000,3.13000,3.30000,3.52000,2.89000,2.94000,3.16000
sulphates,0.5700,0.6300,0.5400,0.86000,0.49000,0.40000,0.51000,0.55000,0.52000,0.630,...,0.59000,1.14000,0.820,1.24000,0.81000,0.89000,1.14000,1.76000,1.54000,1.42000
alcohol,9.0000,8.4000,10.7000,9.90000,11.00000,10.90000,9.80000,9.70000,10.20000,9.950,...,12.20000,9.70000,12.400,9.90000,11.40000,12.00000,9.70000,9.30000,12.90000,13.00000
quality,3.0000,3.0000,3.0000,3.00000,3.00000,3.00000,3.00000,3.00000,3.00000,3.000,...,9.00000,9.00000,9.000,9.00000,9.00000,9.00000,9.00000,9.00000,9.00000,9.00000